name: "Deploy to Production"

on:
    push:
        branches:
            - main
env:
    NODE_VERSION: latest

jobs:
    run-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: oven-sh/setup-bun@v2

          with:
            bun-version: ${{ env.NODE_VERSION}}

        - name: Install dependenices
          run: bun install

        - name: Run unit tests
          run: | 
                bun run test

        - name: Run lint
          run: |
           bun run lint

        - name: Check typecheck
          run: |
              bun run typecheck

        - name: Check build
          run: |
           bun run build

    push-docker-image:
        runs-on: ubuntu-latest
        needs: run-test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login To DockerHub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Check the login
              run: docker info

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Set short SHA
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v7

              with:
                context: .
                push: true
                tags: |
                    ${{ secrets.DOCKER_USERNAME }}/nest-app:latest
                    ${{ secrets.DOCKER_USERNAME }}/nest-app:${{ steps.vars.outputs.sha_short }}

            - name: Scan image for vulnerabilities
              uses: crazy-max/ghaction-container-scan@v4
              with:
                image: ${{ secrets.DOCKER_USERNAME }}/nest-app:latest
            
            - name: Deploy to Production Server
              run: echo "Deploying to Production Server..."

    deploy-image:
        runs-on: ubuntu-latest
        needs: push-docker-image
        steps:
            - name: SSH into Production Server 
              uses: appleboy/ssh-action@v1
              with:
                host: ${{secrets.HOST}}
                username: ${{secrets.AZURE_USERNAME}}
                key: ${{secrets.PASSWORD}}
                script: | 
                    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                    docker pull ${{ secrets.DOCKER_USERNAME }}/nest-app:latest
                    docker stop nest-app || true
                    docker rm nest-app || true
                    docker run -d --name nest-app -p 80:3001 ${{ secrets.DOCKER_USERNAME }}/nest-app:latest
                    

